language: cpp

env:
  global:
    - GLOG_v=1
    - GLOG_logtostderr=1

cache:
  directories:
    - .deps

before_install:
  - cmake -version

install:
  - sudo ./install-deps.sh

script:
  - mkdir -p build
  - cd build
  - cmake .. -DBUILD_CLIENT=OFF
  - make -j$(nproc)
  - ctest --output-on-failure
