dist: bionic
language: cpp
compiler: gcc

env:
  global:
    - GLOG_v=1
    - GLOG_logtostderr=1
    - ENABLE_REPLICATION_DELAY=ON
  jobs:
    - REMASTER_PROTOCOL=NONE
    - REMASTER_PROTOCOL=SIMPLE
    - REMASTER_PROTOCOL=PER_KEY
    - REMASTER_PROTOCOL=COUNTERLESS

cache:
  directories:
    - .deps

install:
  - cd $TRAVIS_BUILD_DIR
  - ./install-deps.sh

script:
  - mkdir -p build
  - cd build
  - cmake -DENABLE_REPLICATION_DELAY=${ENABLE_REPLICATION_DELAY} -DREMASTER_PROTOCOL=${REMASTER_PROTOCOL} -DBUILD_CLIENT=OFF -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release ..
  - make -j$(nproc)
  - ctest --output-on-failure
