dist: focal
language: cpp
compiler: gcc

env:
  global:
    - GLOG_v=4
    - GLOG_logtostderr=1
  jobs:
    - ENABLE_REPLICATION_DELAY=ON REMASTER_PROTOCOL=NONE LOCK_MANAGER=OLD
    - ENABLE_REPLICATION_DELAY=ON REMASTER_PROTOCOL=NONE LOCK_MANAGER=RMA
    - ENABLE_REPLICATION_DELAY=ON REMASTER_PROTOCOL=NONE LOCK_MANAGER=DDR
    - ENABLE_REPLICATION_DELAY=ON REMASTER_PROTOCOL=SIMPLE
    - ENABLE_REPLICATION_DELAY=ON REMASTER_PROTOCOL=PER_KEY
    - ENABLE_REPLICATION_DELAY=ON REMASTER_PROTOCOL=COUNTERLESS LOCK_MANAGER=RMA
    - ENABLE_REPLICATION_DELAY=ON REMASTER_PROTOCOL=COUNTERLESS LOCK_MANAGER=DDR
    - ENABLE_REPLICATION_DELAY=OFF REMASTER_PROTOCOL=NONE LOCK_MANAGER=OLD
    - ENABLE_REPLICATION_DELAY=OFF REMASTER_PROTOCOL=NONE LOCK_MANAGER=RMA
    - ENABLE_REPLICATION_DELAY=OFF REMASTER_PROTOCOL=NONE LOCK_MANAGER=DDR
    - ENABLE_REPLICATION_DELAY=OFF REMASTER_PROTOCOL=SIMPLE
    - ENABLE_REPLICATION_DELAY=OFF REMASTER_PROTOCOL=PER_KEY
    - ENABLE_REPLICATION_DELAY=OFF REMASTER_PROTOCOL=COUNTERLESS LOCK_MANAGER=RMA
    - ENABLE_REPLICATION_DELAY=OFF REMASTER_PROTOCOL=COUNTERLESS LOCK_MANAGER=DDR

script:
  - mkdir -p build
  - cd build
  - cmake -DENABLE_REPLICATION_DELAY=${ENABLE_REPLICATION_DELAY} -DREMASTER_PROTOCOL=${REMASTER_PROTOCOL} -DBUILD_SLOG_CLIENT=OFF -DBUILD_SLOG_TESTS=ON -DCMAKE_BUILD_TYPE=Release ..
  - make -j$(nproc)
  - ctest --output-on-failure
